import os

NUM_CHARGEPOINTS = int(os.getenv('NUM_CHARGEPOINTS', 20))
CHARGING_POWER_KW = int(os.getenv('CHARGING_POWER_KW', 11))
TOTAL_INTERVALS = int(os.getenv('TOTAL_INTERVALS', 35040))
ENERGY_CONSUMPTION_PER_100KM = int(os.getenv('ENERGY_CONSUMPTION_PER_100KM', 18))